apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: sre-platform

resources:
  - namespaces/monitoring.yaml
  - prometheus/rbac.yaml
  - prometheus/configmap.yaml
  - prometheus/rules.yaml
  - prometheus/statefulset.yaml
  - alertmanager/alertmanager.yaml
  - grafana/grafana.yaml
  - workload-policies/hpa-pdb.yaml
